// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package io.grpc;

public final class MyProto {
  private MyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013proto.proto\022\004grpc\"\026\n\007Request\022\013\n\003msg\030\001 " +
      "\001(\t\"\027\n\010Response\022\013\n\003msg\030\001 \001(\t2\317\001\n\005Proto\022+" +
      "\n\010noStream\022\r.grpc.Request\032\016.grpc.Respons" +
      "e\"\000\0222\n\rrequestStream\022\r.grpc.Request\032\016.gr" +
      "pc.Response\"\000(\001\0223\n\016responseStream\022\r.grpc" +
      ".Request\032\016.grpc.Response\"\0000\001\0220\n\tallStrea" +
      "m\022\r.grpc.Request\032\016.grpc.Response\"\000(\0010\001B\032" +
      "\n\007io.grpcB\007MyProtoP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Request_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_Response_descriptor,
        new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
