// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto.proto

package io.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
